---
title: "Data Cleaning for AGB Analysis (Spring 2022)"
author: "Aubrey Knier & Mishka Malinowski"
date: "3/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()

library(tidyverse)
#install.packages("janitor")
library(janitor)

#load data
AGB.sp22.data.raw <- read.csv("Data_USE_ME.csv")
clean.spp.list <- read.csv("clean_spp_list.csv") %>%
  select(Species)
```   

```{r}
#using plots: "DF3B", "DF5A", "DF5B", "DF6A", "DF6B" and "IF2A"

#exploring groups within project and plot columns
unique(AGB.sp22.data.raw$Project)
unique(AGB.sp22.data.raw$Plot)

#filter data for only our 6 plots
AGB.sp22.data <- AGB.sp22.data.raw %>%
  unite("Proj.Plot", Project:Plot, remove=F) %>%
    filter(Proj.Plot %in% c("DF_3B", "DF_5A", "DF_5B", "DF_6A", "DF_6B", "IF_2A"))

#check row names of Proj.Plot
unique(AGB.sp22.data$Proj.Plot) #only data for 6 plots in data frame

#subset data
colnames(AGB.sp22.data)
AGB.sp22.data.subset <- AGB.sp22.data %>%
  select(E, Date..dd.mm.yyyy..1,Proj.Plot,Grid, Plant_tag, X_coord, Y_coord, Tool, POM, DBH..mm., Height..meters.,Type_Field, Note_Field, ID, Treatment)
colnames(AGB.sp22.data.subset)
##QUESTION FOR VINCENT - What is treatment? 

#column names 
colnames(AGB.sp22.data.subset) = c("Data_Collection_Season", "Date", "Proj.Plot", "Grid", "Plant_tag", "X_Coord", "Y_Coord", "Tool", "POM", "DBH_mm", "Height_m", "Veg_Type", "Notes", "ID", "Treatment")

```

```{r}
#### CHECKING COLUMNS ####

#Check Date Column 
class(AGB.sp22.data.subset$Date)
unique(AGB.sp22.data.subset$Date)

AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("3/13/21")] <- "13/03/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("3/14/21")] <- "14/03/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("3/15/21")] <- "15/03/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("3/16/21")] <- "16/03/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("1/12/21")] <- "1/12/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("3/12/21")] <- "3/12/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("2/12/21")] <- "2/12/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("6/12/21")] <- "6/12/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("5/12/21")] <- "5/12/2021"
AGB.sp22.data.subset$Date[AGB.sp22.data.subset$Date %in% c("4/12/21")] <- "4/12/2021"

unique(AGB.sp22.data.subset$Date)

AGB.sp22.data.subset$Date <- as.Date(AGB.sp22.data.subset$Date,
                                     format = "%d/%m/%Y")
class(AGB.sp22.data.subset$Date)
unique(AGB.sp22.data.subset$Date)
summary(AGB.sp22.data.subset$Date)

#Data_Collection_Season
unique(AGB.sp22.data.subset$Data_Collection_Season)
###QUESTION FOR VINCENT - what is the difference between Winter_2021 and Nov_Dec_2021? can you explain these data collection periods more?

#Grid
unique(AGB.sp22.data.subset$Grid)
#Found H7/J8 which is wrong 
class(AGB.sp22.data.subset$Grid)
sum(AGB.sp22.data.subset$Grid == "H7/J8")
AGB.sp22.data.subset$Grid[AGB.sp22.data.subset$Grid %in% c("H7/J8")] <- "H7/I8"

#Plant_tag
unique(AGB.sp22.data.subset$Plant_tag)
TAG_NUM_ID <- AGB.sp22.data.subset %>%
  select(Proj.Plot, Grid, Plant_tag) %>%
  unite("TAG_NUM_2", Proj.Plot:Grid:Plant_tag)

Plant_tag_duplicates <- TAG_NUM_ID %>% group_by(TAG_NUM_2) %>% summarise(n=sum(n())) %>% filter(n>1)
##Well.... even with the most unique identifier we find 1,683 duplicates... so perhaps there was an error with data entry... either in the field or transfering between paper and database

#X_coord 
summary(AGB.sp22.data.subset$X_Coord)
#Looks ok weird that it goes above 5m, but ok 
#why 77 NAs? 
which(is.na(AGB.sp22.data.subset$X_Coord), arr.ind=TRUE)

#Y_coord 
summary(AGB.sp22.data.subset$Y_Coord)
#Looks weirder max at 7...?
which(is.na(AGB.sp22.data.subset$Y_Coord), arr.ind=TRUE)
which(AGB.sp22.data.subset$Y_Coord > "5.0")
#80 NAs
which(is.na(AGB.sp22.data.subset$Y_Coord), arr.ind=TRUE)

#Tool
unique(AGB.sp22.data.subset$Tool)
sum(AGB.sp22.data.subset$Tool == "")
which(AGB.sp22.data.subset$Tool == "")

#POM
summary(AGB.sp22.data.subset$POM)
#seems reasonable but the 154 NAs are meh 

#DBH_mm
summary(AGB.sp22.data.subset$DBH_mm)
#the largest is 2600mm is this reasonable? 
#19 NAs will need to take out then to properly clean 

#Height_mm
summary(AGB.sp22.data.subset$Height_m)
#NAs ok can make model 
class(AGB.sp22.data.subset$Height_m)
nrow(AGB.sp22.data.subset[AGB.sp22.data.subset$Height_m <1.5,])
#should we remove the little ones? They are just taken from the quadrats where we did the little plant sampling.

#Veg_Type
unique(AGB.sp22.data.subset$Veg_Type)
AGB.sp22.data.subset$Veg_Type[AGB.sp22.data.subset$Veg_Type %in% c("tree","TREE")] <- "Tree"
#What should we do about Marantaceae and HRB? 

#Notes
unique(AGB.sp22.data.subset$Notes)

#Treatment
unique(AGB.sp22.data.subset$Treatment)
#Not certain what these are still?

```

``` {r}
#Species IDs

sort(unique(AGB.sp22.data.subset$ID))
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Afrostyrax lepidophloeus")] <- "Afrostyrax lepidophyllus"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae paradoxa")] <- "Agelaea paradoxa"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Xylopia quintesi")] <- "Xylopia quintasii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Xylopia staudti")] <- "Xylopia staudtii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Xylopia ethiopica")] <- "Xylopia aethiopica"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Tricoscypha acuminata")] <- "Trichoscypha acuminata"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Tessmania africana")] <- "Tessmannia africana"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Strombosiopsis tetranda")] <- "Strombosiopsis tetrandra"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Streptogyna crinita")] <- "Streptogyna crinata" # **make sure that these are supposed to be the same spp.
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Sorendea gabonensis")] <- "Sorindeia gabonensis" # **make sure that these are supposed to be the same spp.
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Scotellia klainiana")] <- "Scottellia klaineana"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Scotelia sp 1")] <- "Scottellia sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("salacia sp 1")] <- "Salacia sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Salacia 1A")] <- "Salacia sp 1" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Salacia 1")] <- "Salacia sp 1" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rutacea sp 5")] <- "Rutaceae sp 5" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("rubiaceae sp 1")] <- "Rubiaceae sp 1" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea sp 4")] <- "Rinorea sp 4" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea sp 3")] <- "Rinorea sp 3" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea sp 2")] <- "Rinorea sp 2" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea sp 10")] <- "Rinorea sp 10" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea sp 1")] <- "Rinorea sp 1" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Rhinorea 3")] <- "Rinorea sp 3" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Pseudoposopis giletti")] <- "Pseudoprosopis gilletti" # **confirm which spelling is correct
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Piptadenastrum africana")] <- "Piptadeniastrum africanum" 
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Pentaclethra aetveldiana")] <- "Pentaclethra eetveldeana" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Pausinystalia Johimbe")] <- "Pausinystalia johimbe" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Palusotta hurcita")] <- "Palisota hurcita" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Palisotta ambuga")] <- "Palisota ambuga"
#should "Palisota sp 1" and "Palisota M1" be the same thing?
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Palisota hirsuta")] <- "Palisota hurcita"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Oncoba manni")] <- "Oncoba mannii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Odoniodendron sp 1")] <- "Oddoniodendron sp 1"
#NOTE: "Ochnaceae sp _" is referring to family, not genus
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Napoleona vogellei")] <- "Napoleonaea vogelii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Napoleona vogelei")] <- "Napoleonaea vogelii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Napoleona sp 1")] <- "Napoleonaea sp 1"
# "Morpho" vs "Morpho 001" ?
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Milettia sp 5")] <- "Millettia sp 5"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Milettia sp 4")] <- "Millettia sp 4"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Milettia sp 3")] <- "Millettia sp 3"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Milettia sp 1")] <- "Millettia sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Milettia barteri")] <- "Millettia barteri"
#is "Masoncaria acuminata" supposed to be "Massularia acuminata" ??
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Maesobotria sp 1")] <- "Maesobotrya sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("liane undetermined")] <- "Liane undetermined"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("liane sp 1")] <- "Liane sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Liana undetermined")] <- "Liane undetermined"
# what do do with "Liane", "Liane 1", and "Liane sp 1", for example?
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Lassianthera africana")] <- "Lasianthera africana"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Kleinodoxa gabonensis")] <- "Klainedoxa gabonensis"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Klainodoxa babonensis")] <- "Klainedoxa gabonensis"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Klaineanthus gabonii")] <- "Klaineanthus gaboniae"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Klaineanthus gaboni")] <- "Klaineanthus gaboniae"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Hymenostegia pelegrini")] <- "	
Hymenostegia pellegrinii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Hua gabonii")] <- "Hua gaboni"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Greenwayodendron gabonensis")] <- "Greenwayodendron gabonicum" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Greenwaydendron suavolens")] <- "Greenwayodendron suaveolens"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Greenwaydendron gabonica")] <- "Greenwayodendron gabonicum" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Geophylla sp 1")] <- "Geophila sp 1" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Geophyla afzelli")] <- "Geophila afzelii" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Garcinia smeathmanni")] <- "Garcinia smeathmannii"
# is "Garcinia smickmannii" supposed to be "Garcinia smeathmannii"??
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Funtunia elastica")] <- "Funtumia elastica"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Funtunia africana")] <- "Funtumia africana"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Fillaeopsis discofora")] <- "Fillaeopsis discophora"
#NOTE: i think "fern sp 1" etc. is just referring to any fern, not genus level
#difference between "Fern sp 1" and "Fern Epiphyte sp 1"??
#NOTE: "Fabaceae sp 3" and "Euphorbiacae sp 3" is at family level, not genus
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dubosquia macrocarpa")] <- "Duboscia macrocarpa" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Drypetes gosseweileri")] <- "Drypetes gossweileri"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dismonanthus bentanianus")] <- "Distemonanthus benthamianus"
#NOTE: is "Diospyros oblitifolia" supposed to be the same as "Diospyros obliquifolia" ??
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Diospyros classiflora")] <- "Diospyros crassiflora"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Diogua zenkeri")] <- "Diogoa zenkeri"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dialium denclagei")] <- "Dialium dinklagei" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dialium bipendensis")] <- "Dialium bipindense" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Daniellia Klainei")] <- "Daniellia klainei"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dachriodes normandii")] <- "Dacryodes normandii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dachriodes kleiniana")] <- "Dacryodes klaineana"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Dachriodes butineri")] <- "Dacryodes buettneri"
#NOTE: "Connaraceae sp __" is family level, not genus level
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Cola lisea")] <- "Cola lizae" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Cola edulis")] <- "Coula edulis" # **make sure that these are supposed to be the same
#should "Cola 1" be "Cola sp 1"?
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Coelocaryron preussii")] <- "Coelocaryon preussii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chytranthus talboti")] <- "Chytranthus talbotii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnetis ferruginea")] <- "Cnestis ferruginea"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnestis urens")] <- "Cnestis urens"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnestis sp1")] <- "Cnestis sp1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnestis Irens")] <- "Cnestis irens"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnestis ferruginea")] <- "Cnestis ferruginea"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Chnestis corniculata")] <- "Cnestis corniculata"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Celtis tessmanni")] <- "Celtis tessmannii"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Bredelia sp 1")] <- "Bridelia sp 1"
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Baphia leptobotris")] <- "Baphia leptobotrys"
#NOTE: "Araceae sp __" and "Apocynaceae sp __" and "Annonaceae sp __" and "Anacardiaceae sp __" are families, not genus level
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Annonidium manni")] <- "Anonidium mannii"
#should "Agilocalix 1" be "Agilocalix sp 1" ??
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae poggeana")] <- "Agelaea poggeana" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae sp 9")] <- "Agelaea sp 9" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae sp 3")] <- "Agelaea sp 3" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae sp 2")] <- "Agelaea sp 2" # **make sure that these are supposed to be the same
AGB.sp22.data.subset$ID[AGB.sp22.data.subset$ID %in% c("Agellae sp 1")] <- "Agelaea sp 1" # **make sure that these are supposed to be the same

#compare species ID in dataframe with reference species list. 
inCleanList <- function (x) {
  any(x==clean.spp.list)
}

AGB.sp22.data.subset$Spp.match <- 
  map(AGB.sp22.data.subset$ID, inCleanList)

```
